### ISSUE TITLE
Cannot load pod jaydeesimon/jsoup in macOS arm64 and Linux arm64

### ISSUE THREAD

**Issue by sh54** [babashka/pod-registry#53]
**version**

babashka v1.0.165

**platform**

Both macOS 12.5 on an M2 and virtualized Ubuntu 22.04 LTS arm64 arch.

**problem**

On macOS:

```
Downloading pod jaydeesimon/jsoup (0.1.0)
----- Error --------------------------------------------------------------------
Type:     java.nio.file.NoSuchFileException
Message:  /Users/sh54/.babashka/pods/repository/jaydeesimon/jsoup/0.1.0/mac_os_x/aarch64/META-INF/MANIFEST.MF
Location: /Users/sh54/bin-scripts/./hiccup-html:4:1

----- Context ------------------------------------------------------------------
1: #!/usr/bin/env bb
2: (require '[babashka.pods :as pods])
3:
4: (pods/load-pod 'jaydeesimon/jsoup "0.1.0")
   ^--- /Users/sh54/.babashka/pods/repository/jaydeesimon/jsoup/0.1.0/mac_os_x/aarch64/META-INF/MANIFEST.MF
5:
6: (require '[pod.jaydeesimon.jsoup :as jsoup])
7:
8: (println "done require jsoup")
9:

----- Stack trace --------------------------------------------------------------
babashka.pods.impl.resolver/unzip             - <built-in>
babashka.pods.impl.resolver/resolve/fn--26835 - <built-in>
clojure.core/mapv/fn--8535                    - <built-in>
clojure.core.protocols/fn--8244               - <built-in>
clojure.core.protocols/fn--8204/G--8199--8213 - <built-in>
... (run with --debug to see elided elements)
babashka.pods.sci/load-pod/fn--27053          - <built-in>
babashka.pods.sci/load-pod                    - <built-in>
clojure.core/apply                            - <built-in>
babashka.impl.pods/load-pod                   - <built-in>
```

On Linux:

```
----- Error --------------------------------------------------------------------
Type:     java.lang.IllegalArgumentException
Message:  No executable found for pod jaydeesimon/jsoup (0.1.0) and OS Linux/aarch64
Location: /home/sh54/test/./hiccup-html:4:1

----- Context ------------------------------------------------------------------
1: #!/usr/bin/env bb
2: (require '[babashka.pods :as pods])
3: 
4: (pods/load-pod 'jaydeesimon/jsoup "0.1.0")
   ^--- No executable found for pod jaydeesimon/jsoup (0.1.0) and OS Linux/aarch64
5: 
6: (println "done load pod jsoup")
7: 
8: (require '[pod.jaydeesimon.jsoup :as jsoup])
9: 

----- Stack trace --------------------------------------------------------------
babashka.pods.impl.resolver/match-artifacts - <built-in>
babashka.pods.impl.resolver/resolve         - <built-in>
babashka.pods.impl/resolve-pod              - <built-in>
babashka.pods.impl/load-pod                 - <built-in>
babashka.pods.sci/load-pod/fn--26868        - <built-in>
babashka.pods.sci/load-pod                  - <built-in>
clojure.core/apply                          - <built-in>
babashka.impl.pods/load-pod                 - <built-in>
```
**repro**

```
(require '[babashka.pods :as pods])
(pods/load-pod 'jaydeesimon/jsoup "0.1.0")
```

**expected behavior**

The pod to load correctly. Other pods I have tried like `tzzh/mail` work fine on my machine.

**other notes**

Also I believe [this line](https://github.com/babashka/pod-registry/blob/c2f5c2bc570ef972a6f7288bf866a5f163eaede8/examples/jsoup.clj#L3) should be `(pods/load-pod 'jaydeesimon/jsoup "0.1.0")` instead of `(pods/load-pod 'jaydeesimon/jsoup)`.

**Comment by borkdude** [comment]
Thanks, this looks like a bug. Amd64 should be chosen as a fallback, also on linux probably.

Can you try loading the pod manually by downloading it and loading it with `(load-pod "./the-binary")` ?

**Comment by sh54** [comment]
I have only had luck compiling the pod myself then loading it.

The [zip referenced by the manifest](https://github.com/babashka/pod-registry/blob/c2f5c2bc570ef972a6f7288bf866a5f163eaede8/manifests/jaydeesimon/jsoup/0.1.0/manifest.edn#L10) expands into a bunch of class files but no matching executable. It is just a jar file -  the same as an artifact from the build process just with .zip suffix instead of .jar.

```
wget https://github.com/vollcheck/pod-jaydeesimon-jsoup/releases/download/0.1.0/pod-jaydeesimon-jsoup-0.1.zip
unzip pod-jaydeesimon-jsoup-0.1.zip -d pod
```

Compiling the relevant project then loading the pod artifact worked fine. Though to get it to compile on my machine I had to change [this line](https://github.com/vollcheck/pod-jaydeesimon-jsoup/blob/3f387cdf366cd9cc65e46f2cf3fb6d3017e51dff/script/compile#L13) to `JAR=target/default+uberjar/pod-jaydeesimon-jsoup-0.1-standalone.jar`, though I guess that is an issue for that repo.

**Comment by borkdude** [comment]
@sh54 Oh that doesn't look good indeed. The zip should reference a binary, not a zipped project / .class files.

cc @vollcheck

**Comment by lispyclouds** [comment]
We have removed the pod from the registry until its fixed, [bootleg](https://github.com/retrogradeorbit/bootleg) can be used as an alternative in the meantime.
