### ISSUE TITLE
Release pod-babashka-lanterna 0.0.1

### ISSUE THREAD

**Issue by borkdude** [babashka/pod-registry#7]
We already have a working example: 

https://github.com/babashka/pod-registry/blob/master/examples/lanterna.clj

**Comment by THOUSAND-SKY** [comment]
Hi, is it released yet? The configured url does not have it, at least. What has to be done?

**Comment by borkdude** [comment]
You can download a binary for mac or linux here:

https://app.circleci.com/pipelines/github/babashka/pod-babashka-lanterna

and then run the pod manually with:

```
(pods/load-pod "./local-binary")
```

The lanterna pod is a bit experimental, so it needs testing before release.

**Comment by borkdude** [comment]
Oh right. You need to specify this: 

```
(babashka.pods/load-pod "./pod-babashka-lanterna" {:transport :socket})
```

**Comment by THOUSAND-SKY** [comment]
Thanks! Example works now, I can work with this.

**Comment by borkdude** [comment]
Done releasing 0.0.1
